spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  datasource:
    url: jdbc:h2:mem:test;
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
